"""
F03 — Resolution Replay
Decorator-based action tracer + plain-English compiler + PDF generator.
"""
import functools
import time
import uuid
import logging
from datetime import datetime
from typing import Callable, Any
from collections import defaultdict
from io import BytesIO

logger = logging.getLogger(__name__)

# In-memory trace store: session_id → list of trace dicts
_active_traces: dict[str, list[dict]] = defaultdict(list)

TOOL_DESCRIPTIONS = {
    "check_order_status": "checked your order status",
    "process_refund": "processed a refund",
    "reset_password": "reset your account password",
    "apply_coupon": "applied a discount coupon",
    "escalate_to_human": "escalated your case to a human agent",
    "send_email_confirmation": "sent you a confirmation email",
}


def trace_action(tool_name: str):
    """Decorator that auto-logs every Claude tool call to the trace store."""
    def decorator(fn: Callable):
        @functools.wraps(fn)
        async def wrapper(*args, **kwargs):
            session_id = kwargs.get("session_id", "unknown")
            start = time.time()
            trace_entry = {
                "trace_id": str(uuid.uuid4()),
                "tool_name": tool_name,
                "tool_input": {k: v for k, v in kwargs.items() if k != "session_id"},
                "timestamp": datetime.utcnow().isoformat(),
                "success": False,
                "tool_result": None,
                "duration_ms": 0,
                "error": None,
            }
            try:
                result = await fn(*args, **kwargs)
                trace_entry["tool_result"] = result
                trace_entry["success"] = True
                return result
            except Exception as e:
                trace_entry["error"] = str(e)
                logger.error(f"[F03] Tool {tool_name} failed: {e}")
                raise
            finally:
                trace_entry["duration_ms"] = round((time.time() - start) * 1000, 2)
                _active_traces[session_id].append(trace_entry)

        return wrapper
    return decorator


def get_session_traces(session_id: str) -> list[dict]:
    return _active_traces.get(session_id, [])


def clear_session_traces(session_id: str):
    _active_traces.pop(session_id, None)


def build_trace_plain_english(traces: list[dict]) -> str:
    """Convert raw JSON traces into a human-readable narrative."""
    if not traces:
        return "No actions were recorded for this session."

    lines = ["Here is a complete record of everything Nexus AI did in your session:\n"]
    for i, trace in enumerate(traces, 1):
        tool = trace["tool_name"]
        desc = TOOL_DESCRIPTIONS.get(tool, f"performed: {tool}")
        result = trace.get("tool_result", {})
        success = trace.get("success", True)
        ts = trace.get("timestamp", "")[:19].replace("T", " ")
        duration = trace.get("duration_ms", 0)

        icon = "✓" if success else "✗"
        result_str = ""
        if isinstance(result, dict):
            result_str = " → " + ", ".join(f"{k}: {v}" for k, v in result.items() if k != "session_id")
        elif result:
            result_str = f" → {result}"

        lines.append(f"{icon} Step {i}: I {desc}{result_str} ({duration:.0f}ms at {ts})")

    lines.append("\nThis receipt was automatically generated by Nexus AI.")
    return "\n".join(lines)


def generate_trace_pdf(session_id: str, traces: list[dict], summary_text: str) -> bytes:
    """Generate a styled PDF audit receipt using ReportLab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)

        # Colors
        NEXUS_PURPLE = colors.HexColor("#7C3AED")
        NEXUS_DARK = colors.HexColor("#1E1B4B")
        SUCCESS_GREEN = colors.HexColor("#10B981")
        FAIL_RED = colors.HexColor("#EF4444")
        LIGHT_BG = colors.HexColor("#F5F3FF")

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("title", fontSize=24, textColor=NEXUS_PURPLE, spaceAfter=6, alignment=TA_CENTER, fontName="Helvetica-Bold")
        sub_style = ParagraphStyle("sub", fontSize=11, textColor=colors.grey, spaceAfter=4, alignment=TA_CENTER)
        body_style = ParagraphStyle("body", fontSize=10, textColor=NEXUS_DARK, spaceAfter=4, leading=14)
        label_style = ParagraphStyle("label", fontSize=9, textColor=colors.grey)

        elements = []

        # Header
        elements.append(Paragraph("⚡ Nexus AI", title_style))
        elements.append(Paragraph("Resolution Replay Receipt", sub_style))
        elements.append(Paragraph(f"Session: {session_id}", label_style))
        elements.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", label_style))
        elements.append(HRFlowable(width="100%", thickness=2, color=NEXUS_PURPLE, spaceAfter=12))

        # Summary
        elements.append(Paragraph("Summary", ParagraphStyle("h2", fontSize=14, textColor=NEXUS_DARK, fontName="Helvetica-Bold", spaceAfter=6)))
        elements.append(Paragraph(summary_text.replace("\n", "<br/>"), body_style))
        elements.append(Spacer(1, 0.5*cm))

        # Action Table
        if traces:
            elements.append(Paragraph("Detailed Action Log", ParagraphStyle("h2", fontSize=14, textColor=NEXUS_DARK, fontName="Helvetica-Bold", spaceAfter=6)))

            table_data = [["#", "Action", "Result", "Status", "Duration", "Time"]]
            for i, trace in enumerate(traces, 1):
                result = trace.get("tool_result", {})
                result_str = ""
                if isinstance(result, dict):
                    result_str = "; ".join(f"{k}={v}" for k, v in list(result.items())[:2])
                elif result:
                    result_str = str(result)[:50]
                status = "✓ Success" if trace.get("success") else "✗ Failed"
                ts = trace.get("timestamp", "")[:19]
                duration = f"{trace.get('duration_ms', 0):.0f}ms"
                table_data.append([
                    str(i),
                    TOOL_DESCRIPTIONS.get(trace["tool_name"], trace["tool_name"]),
                    result_str[:60],
                    status,
                    duration,
                    ts[11:] if len(ts) > 11 else ts,
                ])

            col_widths = [1*cm, 4.5*cm, 5*cm, 2.5*cm, 2*cm, 2*cm]
            table = Table(table_data, colWidths=col_widths, repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), NEXUS_PURPLE),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(table)

        elements.append(Spacer(1, 1*cm))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
        elements.append(Paragraph("This document is an auto-generated AI audit receipt from Nexus AI.", label_style))

        doc.build(elements)
        return buffer.getvalue()

    except ImportError:
        # ReportLab not installed — return minimal PDF placeholder
        return b"%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF"
